controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    pid_gains:
      shoulder_pan_joint:
        p: 100.0
        i: 0.01
        d: 10.0
      shoulder_lift_joint:
        p: 100.0
        i: 0.01
        d: 10.0
      elbow_joint:
        p: 100.0
        i: 0.01
        d: 10.0
      wrist_1_joint:
        p: 100.0
        i: 0.01
        d: 10.0
      wrist_2_joint:
        p: 100.0
        i: 0.01
        d: 10.0
      wrist_3_joint:
        p: 100.0
        i: 0.01
        d: 10.0
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger1_joint