global_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 5.0 #before: 5.0
  publish_frequency: 0.5 #before 0.5
  static_map: true
  transform_tolerance: 0.2
  cost_scaling_factor: 4.0
  inflation_radius: 0.7
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.04