local_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 5.0 #before 5.0
  publish_frequency: 2.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 1.0
  height: 1.0
  resolution: 0.025 #increase to for higher res 0.025
  transform_tolerance: 0.2
  cost_scaling_factor: 6.0
  inflation_radius: 0.7
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.04