TrajectoryPlannerROS:
  max_vel_x: 2.5
  meter_scoring: true
  min_vel_x: 0.01
  max_vel_theta: 3.0
  min_vel_theta: -3.0
  min_in_place_vel_theta: 0.5
  acc_lim_theta: 0.6
  escape_vel: -0.3 
  acc_lim_x: 3.0
  acc_lim_y: 3.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.06
  holonomic_robot: false
  scaling_speed: 1.5
  sim_time: 0.9

# TrajectoryPlannerROS:
#   max_vel_x: 1.4 #0.6 #0.9 #1.2
#   meter_scoring: true
#   min_vel_x: 0.5 #0.25 #0.4 #0.5 #0.6
#   max_vel_theta: 0.9 #0.6 #0.9
#   min_vel_theta: -0.6 #-0.6 #-0.8
#   backup_vel: -0.15
#   escape_vel: -0.15  
#   min_in_place_vel_theta: 0.5 #0.25 #0.3 #0.5
#   acc_lim_theta: 1.5 
#   acc_lim_x: 2 #2 #2.5 #2.3
#   acc_lim_y: 2 #2 #2.5 #2.3
#   xy_goal_tolerance: 0.25 #0.25
#   yaw_goal_tolerance: 0.04 #0.05
#   holonomic_robot: false
#   scaling_speed: 0.3
#   sim_time: 0.65